// Code generated by engine.go; DO NOT EDIT.

package provider
import (
	"k8s.io/kops/pkg/apis/kops"
)


func flattenSSHCredentialSpec(in kops.SSHCredentialSpec) []map[string]interface{} {
	out := make([]map[string]interface{}, 1)

	for i := 0; i < len(out); i++ {
		out[i] = make(map[string]interface{})

		if 	in.PublicKey != "" {
			out[i]["public_key"] = flattenString(in.PublicKey)
		}
	}

	return out
}
