// Code generated by engine.go; DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform/helper/schema"
)

func resourceSSHCredential() *schema.Resource {
	return &schema.Resource{
		Create: resourceSSHCredentialCreate,
		Read:   resourceSSHCredentialRead,
		Update: resourceSSHCredentialUpdate,
		Delete: resourceSSHCredentialDelete,
		Exists: resourceSSHCredentialExists,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"api_version": schemaOptionalString(),
			"kind": schemaOptionalString(),
			"metadata": schemaObjectMeta(),
			"spec": schemaSSHCredentialSpec(),
		},
	}
}

func datasourceSSHCredential() *schema.Resource {
	return &schema.Resource{
		Read: resourceSSHCredentialRead,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"api_version": schemaOptionalString(),
			"kind": schemaOptionalString(),
			"metadata": schemaObjectMeta(),
			"spec": schemaSSHCredentialSpec(),
		},
	}
}

func schemaSSHCredentialSpec() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		MaxItems: 1,
		Optional: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"public_key": schemaOptionalString(),
			},
		},
	}
}