name: terraform-provider-kops -> Test & Build
on: 
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Dry-Run
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Validates GO releaser config
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: check

    - name: Create release dry-run
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: release --skip-publish
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
