name: terraform-provider-kops -> Test & Build
on: 
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Dry-Run
    steps:
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Create release dry-run
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: release --skip-publish
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
